//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluToDo {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalLocation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalLocation() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluToDo.GlobalLocation", typeof(GlobalLocation).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        internal static string AddText {
            get {
                return ResourceManager.GetString("AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error has ocurred creating.
        /// </summary>
        internal static string ErrorAdd {
            get {
                return ResourceManager.GetString("ErrorAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error has ocurred deleting.
        /// </summary>
        internal static string ErrorDelete {
            get {
                return ResourceManager.GetString("ErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error has ocurred getting ToDoItems from server. Check internet connection..
        /// </summary>
        internal static string ErrorGet {
            get {
                return ResourceManager.GetString("ErrorGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error has ocurred updating ToDoItem .
        /// </summary>
        internal static string ErrorPut {
            get {
                return ResourceManager.GetString("ErrorPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ToDo Detail.
        /// </summary>
        internal static string FluToDoDetailTitle {
            get {
                return ResourceManager.GetString("FluToDoDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FluToDo.
        /// </summary>
        internal static string FluToDoTitle {
            get {
                return ResourceManager.GetString("FluToDoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a created on server successfully!.
        /// </summary>
        internal static string SuccessAdd {
            get {
                return ResourceManager.GetString("SuccessAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a deleted from server successfully!.
        /// </summary>
        internal static string SuccessDelete {
            get {
                return ResourceManager.GetString("SuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a updated on server successfully!.
        /// </summary>
        internal static string SuccessPut {
            get {
                return ResourceManager.GetString("SuccessPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter description....
        /// </summary>
        internal static string ToDoEntryPlaceHolder {
            get {
                return ResourceManager.GetString("ToDoEntryPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ToDo:.
        /// </summary>
        internal static string ToDoHeader {
            get {
                return ResourceManager.GetString("ToDoHeader", resourceCulture);
            }
        }
    }
}
